### PR TITLE
remove backtick due to incompatibility with ie11

### PR DESCRIPTION
**Pull request by mvcds**
I needed to support ie11 for a client and locally I had done this change, now I am forking and committing it.

Let me know if you want something more elaborate, like a flag to control whether or not support that _lovely_ browser.

### CODE REVIEW

**Comment by sionzee** [comment]
Hey! Sorry for late response. I haven't received notification.
This change definitely makes sense! Thank you for your PR!

It needs a little bit more changes because single quote is valid html character.
eg.: `<svg attr='test'>` and it will break your change because the output will be:
```javascript
export default '<svg attr='test'>...</svg>'
```
So I suggest to escape all single quote with escape character `\`.

I will accept the merge and modify it! Thank you very much.

**Comment by sionzee** [comment]
@mvcds Hey! I have release 2.0.0 with more fixes. If you are still interested please let me know if it works for you.
Thank you. 🍻

**Comment by mvcds** [comment]
Cool. I'll have holidays now so I cannot check for about one month. Is there anything I can help you later?

**Comment by sionzee** [comment]
That is fine! Enjoy your holidays! 🎉

**Pull request merged**
